In [1]:
# from src.games.uttt.game import game 
import src.games.uttt.game as game
from importlib import reload
reload(game)
import numpy as np

In [11]:
import unittest

In [7]:
[range(3)]*4

[range(0, 3), range(0, 3), range(0, 3), range(0, 3)]

In [12]:
unittest.TestCase().assertSequenceEqual(mb.valid_moves(),np.array(np.meshgrid(*[range(3)]*4)).T.reshape(-1,4))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [23]:
sorted(np.array(np.meshgrid(*[range(3)]*4)).T.reshape(-1,4).tolist()) == sorted(mb.valid_moves().tolist())

True

In [20]:
sorted(mb.valid_moves().tolist())

[[0, 0, 0, 0],
 [0, 0, 0, 1],
 [0, 0, 0, 2],
 [0, 0, 1, 0],
 [0, 0, 1, 1],
 [0, 0, 1, 2],
 [0, 0, 2, 0],
 [0, 0, 2, 1],
 [0, 0, 2, 2],
 [0, 1, 0, 0],
 [0, 1, 0, 1],
 [0, 1, 0, 2],
 [0, 1, 1, 0],
 [0, 1, 1, 1],
 [0, 1, 1, 2],
 [0, 1, 2, 0],
 [0, 1, 2, 1],
 [0, 1, 2, 2],
 [0, 2, 0, 0],
 [0, 2, 0, 1],
 [0, 2, 0, 2],
 [0, 2, 1, 0],
 [0, 2, 1, 1],
 [0, 2, 1, 2],
 [0, 2, 2, 0],
 [0, 2, 2, 1],
 [0, 2, 2, 2],
 [1, 0, 0, 0],
 [1, 0, 0, 1],
 [1, 0, 0, 2],
 [1, 0, 1, 0],
 [1, 0, 1, 1],
 [1, 0, 1, 2],
 [1, 0, 2, 0],
 [1, 0, 2, 1],
 [1, 0, 2, 2],
 [1, 1, 0, 0],
 [1, 1, 0, 1],
 [1, 1, 0, 2],
 [1, 1, 1, 0],
 [1, 1, 1, 1],
 [1, 1, 1, 2],
 [1, 1, 2, 0],
 [1, 1, 2, 1],
 [1, 1, 2, 2],
 [1, 2, 0, 0],
 [1, 2, 0, 1],
 [1, 2, 0, 2],
 [1, 2, 1, 0],
 [1, 2, 1, 1],
 [1, 2, 1, 2],
 [1, 2, 2, 0],
 [1, 2, 2, 1],
 [1, 2, 2, 2],
 [2, 0, 0, 0],
 [2, 0, 0, 1],
 [2, 0, 0, 2],
 [2, 0, 1, 0],
 [2, 0, 1, 1],
 [2, 0, 1, 2],
 [2, 0, 2, 0],
 [2, 0, 2, 1],
 [2, 0, 2, 2],
 [2, 1, 0, 0],
 [2, 1, 0, 1],
 [2, 1, 0, 2],
 [2, 1, 1,

In [15]:
mb = game.UTTTState()
mb.valid_moves()
sorted(list(mb.valid_moves()))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
np.array(np.meshgrid(*[range(3)]*4)).T.reshape(-1,4)

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 2, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 2, 0, 0],
       [2, 0, 0, 0],
       [2, 1, 0, 0],
       [2, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 0],
       [0, 2, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 1, 0],
       [1, 2, 1, 0],
       [2, 0, 1, 0],
       [2, 1, 1, 0],
       [2, 2, 1, 0],
       [0, 0, 2, 0],
       [0, 1, 2, 0],
       [0, 2, 2, 0],
       [1, 0, 2, 0],
       [1, 1, 2, 0],
       [1, 2, 2, 0],
       [2, 0, 2, 0],
       [2, 1, 2, 0],
       [2, 2, 2, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 1],
       [0, 2, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 2, 0, 1],
       [2, 0, 0, 1],
       [2, 1, 0, 1],
       [2, 2, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 1],
       [0, 2, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 2, 1, 1],
       [2, 0, 1, 1],
       [2, 1, 1, 1],
       [2, 2, 1, 1],
       [0, 0, 2, 1],
       [0, 1, 2, 1],
       [0, 2,

In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
mb = game.UTTTState()

In [10]:
completed_subs = np.array([[0,0],[0,2]])

In [33]:
np.array([[0,1]]) == np.array([[3],[0]])

array([[False, False],
       [ True, False]])

In [39]:
test

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [2, 0],
       [2, 0],
       [2, 0],
       [2, 0],
       [2, 0],
       [2, 0],
       [2, 0],
       [2, 0],
       [2, 0],
       [2, 1],
       [2, 1],
       [2, 1],
       [2,

In [38]:
np.expand_dims(np.expand_dims(completed_subs.T,-1), -1)

array([[[[0]],

        [[0]]],


       [[[0]],

        [[2]]]])

In [43]:
np.expand_dims(np.expand_dims(completed_subs.T,-1), -1).shape
a = np.expand_dims(np.expand_dims(completed_subs.T,-1), -1) == test
a.shape
np.expand_dims(np.expand_dims(completed_subs.T,-1), -1) == test
np.logical_and.reduce(np.expand_dims(np.expand_dims(completed_subs.T,-1), -1) == test,axis=-1).shape
# np.logical_and.reduce(np.expand_dims(np.expand_dims(completed_subs.T,-1), -1) == test,axis=-1)

(2, 2, 1, 1)

(2, 2, 81, 2)

array([[[[ True,  True],
         [ True,  True],
         [ True,  True],
         [ True,  True],
         [ True,  True],
         [ True,  True],
         [ True,  True],
         [ True,  True],
         [ True,  True],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [ True, False],
         [False,  True],
         [False,  True],
         [False,  True],
         [False,  True],
         [False,  True],
         [False,  True],
         [False,  True],
         [False,  True],
         [False,  True],
         [False, False],
         [False, False],
         [False, False],
         [False, False],


(2, 2, 81)

In [44]:
np.logical_and.reduce(np.expand_dims(np.expand_dims(completed_subs.T,-1), -1) == test,axis=-1).shape
np.logical_and.reduce(np.expand_dims(np.expand_dims(completed_subs.T,-1), -1) == test,axis=-1)

(2, 2, 81)

array([[[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False

In [35]:
test.shape

(81, 2)

In [31]:
np.expand_dims(np.expand_dims(completed_subs.T,0), 0) == test

/home/gergely/miniconda3/envs/gomoku/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [25]:
test = np.argwhere(mb.board==0)[:,:2]
test.shape

(81, 2)

In [24]:
np.argwhere(mb.board==0)[:,:2]==completed_subs

/home/gergely/miniconda3/envs/gomoku/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [20]:
completed_subs
np.argwhere(mb.board==0)[:,:2][0]
np.argwhere(mb.board==0)[:,:2][0] in completed_subs

array([[0, 0],
       [0, 2]])

array([0, 0])

True

In [21]:
np.isin(np.argwhere(mb.board==0)[:,:2],completed_subs)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [Fal

In [9]:
np.argwhere(mb.board==0)

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [0, 0, 2, 0],
       [0, 0, 2, 1],
       [0, 0, 2, 2],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 2],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 1, 2],
       [0, 1, 2, 0],
       [0, 1, 2, 1],
       [0, 1, 2, 2],
       [0, 2, 0, 0],
       [0, 2, 0, 1],
       [0, 2, 0, 2],
       [0, 2, 1, 0],
       [0, 2, 1, 1],
       [0, 2, 1, 2],
       [0, 2, 2, 0],
       [0, 2, 2, 1],
       [0, 2, 2, 2],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 2],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 2],
       [1, 0, 2, 0],
       [1, 0, 2, 1],
       [1, 0, 2, 2],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 0, 2],
       [1, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 2, 0],
       [1, 1, 2, 1],
       [1, 1, 2, 2],
       [1, 2, 0, 0],
       [1, 2, 0, 1],
       [1, 2,

In [30]:
    move = input()
    print(move)
    array_move = np.array(move)
    print(array_move)

0,0,0,0
0,0,0,0
0,0,0,0


In [34]:
array_move

array('0,0,0,0',
      dtype='<U7')

In [39]:
np.array(range(16)).reshape(2,2,2,2)
np.array(range(16)).reshape(4,4)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [6]:
def input_to_array(inp):
    doubleindex = int(inp)
    second = doubleindex % 10
    firstindex = doubleindex // 10
    one = firstindex // 3
    sec = firstindex % 3
    third = second // 3
    fourth = second % 3
    return (one,sec,third,fourth)
input_to_array(66)

(2, 0, 2, 0)

In [64]:
mb.global_wins

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [7]:
mb = game.UTTTState()
while not mb.is_over():
    print("Active subgame is {}".format(mb.active_subgame))
    move = input()
    print(move)
    array_move = input_to_array(move)
    print(array_move)
    mb = mb.move(array_move)
    print(mb)

Active subgame is None
66
66
(2, 0, 2, 0)


TypeError: only integer scalar arrays can be converted to a scalar index

In [75]:
a = np.array(range(4)).reshape(2,2)
a[2,:] =6

IndexError: index 2 is out of bounds for axis 0 with size 2

In [56]:
good_pos = mb.board==0

In [72]:
mb.global_wins!=0

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [71]:
mb.board==0

array([[[[False, False,  True],
         [False, False,  True],
         [ True, False,  True]],

        [[False,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[False,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[False,  True,  True],
         [ True, False, False],
         [ True,  True, False]],

        [[ True,  True,  True],
         [ True, False,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True, False,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]]])

In [60]:
mb.board[mb.global_wins!=0]

array([[[ 1., -1.,  0.],
        [-1., -1.,  0.],
        [ 0., -1.,  0.]]])

In [70]:
np.argwhere(good_pos)

array([[0, 1, 0, 1],
       [0, 1, 0, 2],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 1, 2],
       [0, 1, 2, 0],
       [0, 1, 2, 1],
       [0, 1, 2, 2],
       [0, 2, 0, 0],
       [0, 2, 0, 1],
       [0, 2, 0, 2],
       [0, 2, 1, 0],
       [0, 2, 1, 1],
       [0, 2, 1, 2],
       [0, 2, 2, 0],
       [0, 2, 2, 1],
       [0, 2, 2, 2],
       [1, 0, 0, 1],
       [1, 0, 0, 2],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 2],
       [1, 0, 2, 0],
       [1, 0, 2, 1],
       [1, 0, 2, 2],
       [1, 1, 0, 1],
       [1, 1, 0, 2],
       [1, 1, 1, 0],
       [1, 1, 2, 0],
       [1, 1, 2, 1],
       [1, 2, 0, 0],
       [1, 2, 0, 1],
       [1, 2, 0, 2],
       [1, 2, 1, 0],
       [1, 2, 1, 2],
       [1, 2, 2, 0],
       [1, 2, 2, 1],
       [1, 2, 2, 2],
       [2, 0, 0, 0],
       [2, 0, 0, 1],
       [2, 0, 0, 2],
       [2, 0, 1, 0],
       [2, 0, 1, 1],
       [2, 0, 1, 2],
       [2, 0, 2, 0],
       [2, 0, 2, 1],
       [2, 0, 2, 2],
       [2, 1,

In [68]:
good_pos
mb.global_wins!=0
good_pos[mb.global_wins!=0] = False

array([[[[False, False, False],
         [False, False, False],
         [False, False, False]],

        [[False,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[False,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[False,  True,  True],
         [ True, False, False],
         [ True,  True, False]],

        [[ True,  True,  True],
         [ True, False,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True, False,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]]])

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [54]:
np.nonzero(mb.board)
np.where(mb.board==0)


(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 2, 1]),
 array([0, 0, 1, 1, 2, 0, 0, 0, 1, 1, 2, 1, 1]),
 array([0, 1, 0, 1, 1, 0, 0, 0, 1, 2, 2, 1, 1]))

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]),
 array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
        2, 2]),
 array([0, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0,
        0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 2, 0, 0,
        0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2,
        2, 2]),
 array([2, 2, 0, 2, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 1,
        2, 0, 1, 2, 0, 1, 2, 1, 2, 0, 0, 1, 0, 1, 2, 0, 2, 0, 1, 2, 0, 1,
        2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2]))

In [49]:
print(mb)

1 -1 0 | 1 0 0 | 0 0 0 
-1 -1 0 | 0 0 0 | 0 0 0 
0 -1 0 | 0 0 0 | 0 0 0 
- - - | - - - | - - - 
1 0 0 | 1 0 0 | 0 0 0 
0 0 0 | 0 -1 1 | 0 -1 0 
0 0 0 | 0 0 1 | 0 0 0 
- - - | - - - | - - - 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 1 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 



In [49]:
array_move

array([2, 0, 2, 0])

In [48]:
mb.board[array_move]

array([[[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]]])

In [46]:
mb.is_forbidden_move(array_move)

array([[[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]]])

In [23]:
print(mb)

0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
- - - | - - - | - - - 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
- - - | - - - | - - - 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 



In [12]:
len(mb.board)

3

In [11]:
[x for x in mb.board][0]

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [19]:
print(str(mb))

0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
- - - | - - - | - - - 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
- - - | - - - | - - - 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 



In [33]:
board = np.zeros((3,)*4)

In [35]:
not 4`b


False

In [38]:
class ASD:
    D = 4
    D = D*2

In [43]:
ASD().D

8

In [54]:
a[[[0,0]]]

array([[1, 2],
       [1, 2]])

In [58]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
a=  np.array(range(9)).reshape(3,3)
np.where(a>4)
indices = [x for x in np.argwhere(a>4)]

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [86]:
a[np.expand_dims(indices[0],1)]

array([[[3, 4, 5]],

       [[6, 7, 8]]])

In [92]:
z = np.array([[[ 0,  1,  2,  3],
...                [ 4,  5,  6,  7],
...                [ 8,  9, 10, 11]],
...
...               [[12, 13, 14, 15],
...                [16, 17, 18, 19],
...                [20, 21, 22, 23]]])

In [103]:
z[[[0,0,0],[1,1,1]],[[0,1,2],[0,1,2]],[[0,1,2],[0,1,2]]]

array([[ 0,  5, 10],
       [12, 17, 22]])

In [170]:
z[*indices[0],slice(None)]

SyntaxError: invalid syntax (<ipython-input-170-1d480512b5c0>, line 1)

In [111]:
z[((1,0,1),)]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [126]:
slice(None)

slice(None, None, None)

In [132]:
a[asd]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [136]:
asd[0] = [0,1]

ValueError: setting an array element with a sequence.

In [141]:
np.nonzero(a>4)
np.transpose(np.nonzero(a>4))

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

array([[1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

In [163]:
a = [1,2,3]
a[slice(None)]

[1, 2, 3]

In [164]:
np.array([1,2,slice(None)])

array([1, 2, slice(None, None, None)], dtype=object)

In [161]:
ind
tuple(ind)
ind[1] = [0,1]

array([[1],
       [2]])

(array([1]), array([2]))

ValueError: cannot copy sequence with size 2 to array axis with dimension 1

In [158]:
np.put(ind,[1],slice(None))

TypeError: int() argument must be a string, a bytes-like object or a number, not 'slice'

In [4]:
mb.__dict__

NameError: name 'mb' is not defined

In [151]:
np.argwhere(a>4)
asd = np.argwhere(a>4)[0]
asd
asd[0]
a[tuple(asd)]
ind = np.expand_dims(asd,1)
ind
ind.shape
ind[1,0] = slice(None)

array([[1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

array([1, 2])

1

5

array([[1],
       [2]])

(2, 1)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'slice'

In [119]:
np.nonzero(a>5)
np.transpose(np.where(a>5))
np.transpose(np.where(a>5))[0]

(array([2, 2, 2]), array([0, 1, 2]))

array([[2, 0],
       [2, 1],
       [2, 2]])

array([2, 0])

In [106]:
a
indices[0]
np.expand_dims(indices[0],1)
tuple(np.expand_dims(indices[0],1))
a[tuple(np.expand_dims(indices[0],1))]
a[(np.expand_dims(indices[0],1))]
np.transpose(indices[0])
a[indices[0]]
a[[indices[0]]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([1, 2])

array([[1],
       [2]])

(array([1]), array([2]))

array([5])

array([[[3, 4, 5]],

       [[6, 7, 8]]])

array([1, 2])

array([[3, 4, 5],
       [6, 7, 8]])

array([[3, 4, 5],
       [6, 7, 8]])

In [76]:
a[np.transpose(indices[0])]

array([[3, 4, 5],
       [6, 7, 8]])

In [57]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
x
y

array([1, 4, 5])

In [49]:
index[1] = slice(None,None,None)


TypeError: 'tuple' object does not support item assignment

In [62]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [47]:
a = np.array([[1,2],[3,4]])
index = np.where(a==1)
a[index]

array([1])

In [34]:
board`a


array([[[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]]])

In [21]:
import numpy as np

np.array(mb.board)

array([[<src.games.uttt.sub_board.SubBoard object at 0x7feceafdb080>,
        <src.games.uttt.sub_board.SubBoard object at 0x7feceafd7780>]], dtype=object)

In [31]:
list(map(lambda x:np.float(x.played_by), (cell for row in mb.board[0][0] for cell in row)))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [32]:
(np.float(cell.played_by) for row in mb.board[0][0] for cell in row)

<generator object <genexpr> at 0x7fed18e5c990>

In [18]:
print(mb)

0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
- - - | - - - | - - - 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
- - - | - - - | - - - 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 
0 0 0 | 0 0 0 | 0 0 0 



In [ ]:
from importlib import reload
import src.trainer
reload(src.trainer)
from src.trainer import Trainer
coach = Trainer('gomoku')

In [ ]:
coach.learn()

In [2]:
from src.arena import Arena
from src.agents.human import HumanAgent
from src.agents.student import StudentAgent
from src.agents.random import RandomAgent
from src.games.gomoku.neural_net import GomokuNN
import src.agents.random as _random
# reload(_random)
#b = GomokuNN('gomokunew_checkpoint_20')
#s = StudentAgent(b)
#h = HumanAgent()
r = _random.RandomAgent()
a = Arena('uttt',r,r)

In [4]:
wins, history = a.war(100)

Arena: 100%|██████████| 100/100 [00:01<00:00, 63.55it/s]


In [6]:
history

[[[array([2, 2, 2, 2]),
   array([1, 2]),
   array([0, 1]),
   array([0, 1]),
   array([1, 1]),
   array([1, 0]),
   array([1, 0]),
   array([0, 2]),
   array([2, 0]),
   array([1, 2]),
   array([2, 2]),
   array([0, 2]),
   array([1, 0]),
   array([2, 1]),
   array([0, 1]),
   array([2, 2]),
   array([1, 0]),
   array([1, 2]),
   array([2, 0]),
   array([0, 2]),
   array([0, 1]),
   array([2, 0]),
   array([2, 2]),
   array([1, 1]),
   array([2, 0]),
   array([1, 1]),
   array([0, 0]),
   array([1, 0]),
   array([0, 0]),
   array([1, 2]),
   array([0, 2]),
   array([0, 0]),
   array([2, 2]),
   array([0, 1]),
   array([1, 0]),
   array([2, 2]),
   array([0, 0]),
   array([0, 1]),
   array([1, 2]),
   array([1, 0]),
   array([1, 1, 1, 1]),
   array([2, 2]),
   array([2, 1]),
   array([2, 2]),
   array([2, 0]),
   array([2, 1]),
   array([2, 1]),
   array([0, 0]),
   array([0, 2]),
   array([1, 2]),
   array([0, 0]),
   array([2, 1]),
   array([0, 2]),
   array([2, 1]),
   array([1, 0])

In [5]:
wins

array([ 97., 103.])

In [13]:
import numpy as np
np.array(history)[:,0]

array([list([0, 3, 5, 2, 4, 6, 8]), list([5, 0, 7, 8, 4, 2, 1]),
       list([8, 6, 7, 1, 3, 2, 5, 0]), list([6, 5, 0, 1, 3]),
       list([4, 2, 7, 6, 1]), list([0, 3, 5, 6, 8, 4, 2]),
       list([8, 7, 3, 4, 5, 6, 2]), list([8, 2, 0, 1, 5, 4, 3, 6]),
       list([7, 4, 5, 3, 1, 8, 0, 2, 6]), list([8, 5, 1, 3, 0, 2, 4])], dtype=object)

In [1]:
import numpy as np
possible_move_len = 9
np.full((possible_move_len, ), 1./possible_move_len)

array([ 0.11111111,  0.11111111,  0.11111111,  0.11111111,  0.11111111,
        0.11111111,  0.11111111,  0.11111111,  0.11111111])